# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
