# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171110_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='home.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(default='shashank', max_length=100),
        ),
    ]
