# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171112_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User', max_length=200),
        ),
    ]
